### ISSUE TITLE
Search in Dynamic List should be possible

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluFormBundle#11]
The dynamic list should also be searchable.

**Comment by simontol** [comment]
Hi @alexander-schranz , 
this seems not to work because the request is missing `searchFields` param

`vendor/sulu/form-bundle/Repository/DynamicRepository.php`

``` 
   protected function addSearchFilter(QueryBuilder $queryBuilder, ?string $search, ?array $searchFields): void
    {
        if (empty($search) || empty($searchFields)) {
            return;
        }
```

It works adding `&searchParams=data` to the `/admin/api/form/dynamics` request
