### ISSUE TITLE
Compatibility Sulu form checksum with kernel secret

### ISSUE THREAD

**Issue by nvdbeek** [sulu/SuluFormBundle#110]
We are using `.env` files for defining the APP_DEBUG, APP_ENV and APP_SECRET. With this we load the APP_SECRET into the `config.yml` under framework: secret (`secret: '%env(APP_SECRET)%'`) and not in `parameters.yml` or as parameters in the `config.yml`.

When I load the sulu form bundle I am getting the following error:
`The service "sulu_form.checksum" has a dependency on a non-existent parameter "secret". Did you mean this: "kernel.secret"?`

**How to fix this?**
Change the `sulu.form.checksum` to use the `kernel.secret`.

We can made a tempory fix for solving this by setting the secret as parameters in `parameters.yml` or parameters in `config.yml`. My preference is not to setting it this way.

**Comment by wachterjohannes** [comment]
@alexander-schranz could you maybe answer this question?

**Comment by alexander-schranz** [comment]
@nvdbeek thank you for reporting this is definitly a bug we need to fix.
