### ISSUE TITLE
Field placeholder contains "false" when left empty on creation.

### ISSUE THREAD

**Issue by nwaelkens** [sulu/SuluFormBundle#138]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | 0a1db8d75c06cba0f347931c356bbbdb91fd4b8d (master)
| Sulu Version | 1.6.12
| Browser Version | Safari

#### Actual Behavior
I get to see 'false' as placeholder (in front and backend) when I leave the field 'example' empty upon creation of a dynaform. 

#### Expected Behavior
If I leave 'example' empty there should not be any placeholder value. 

#### Steps to Reproduce
Create a new field (block) in a form and leave the placeholder / example field empty. Save form. The field contains now the value 'false'. 

#### Possible Solutions
Don't let the method getPlaceholder() ever return 'false' in Entity/FormFieldTranslation.php. This value is 'stringified' somewhere I guess.

**Comment by alexander-schranz** [comment]
Hello @nwaelkens,
Thank you for your report. Can you also tell me the Symfony Version and your theme or is it also when you just use the `SuluFormBundle:themes:dynamic.html.twig` also?

**Comment by nwaelkens** [comment]
SF version: 3.4.2
I use the default theme: 
`{% form_theme content.form 'SuluFormBundle:themes:dynamic.html.twig' %}`

**Comment by alexander-schranz** [comment]
fixed in
