### ISSUE TITLE
Save-button disabled after adding only a new block/field

### ISSUE THREAD

**Issue by nwaelkens** [sulu/SuluFormBundle#139]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | 0a1db8d75c06cba0f347931c356bbbdb91fd4b8d (master)
| Sulu Version | 1.6.12
| Browser Version | Safari

#### Actual Behavior
When I edit a form and only add a field (without changing anything else) the 'save-button' stays disabled. 

#### Expected Behaviour
Adding a field /block is a change and should make the 'save-button' available.

#### Steps to Reproduce
Edit an existing form, add a block/field and try to save.

**Comment by alexander-schranz** [comment]
fixed in #141
