### ISSUE TITLE
Mandatory field on checkboxes

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/SuluFormBundle#14]
If i create a form field with `checkboxes` and set it as mandatory-field, nothing happens. The fields aren't declared as `required`.

Please remove the mandatory field marker from the checkboxes or set the attribute to every checkbox in checkboxes.

**Comment by alexander-schranz** [comment]
single or multiple checkboxes?

**Comment by dmetzler1988** [comment]
multiple checkboxes :)

**Comment by alexander-schranz** [comment]
@dmetzler1988 the multiple checkboxes can't have required in the input this would make all options as required not only one http://jsfiddle.net/tw1yz04t/ as the form bundle should work without JS you need to implement this yourself.
