### ISSUE TITLE
Mandatory field on select

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/SuluFormBundle#15]
It's a issue in case of "bug" from symfony2 form theme.

If we have marked a select field (salutation) as mandatory field, symfony2 removes the required attribute from select (because no default option with empty value exist). 
In this case the select field wouldn't be marked as required - only the label will be marked as required.

It isn't a important issue.

**Comment by alexander-schranz** [comment]
Tested with symfony 3 this issue not longer exist so upgrade your project to symfony 3 should fix the problem.
