### ISSUE TITLE
Copy function of existing forms 

### ISSUE THREAD

**Issue by cedric-gunz** [sulu/SuluFormBundle#151]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | Specific version or SHA of a commit
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

How does it behave at the moment? 
At the moment, you have to rebuild every list, every time.

#### Expected Behavior

What is the behavior you expect?
It will save the user a lot of time!

#### Steps to Reproduce

![image](https://user-images.githubusercontent.com/37687604/37816268-bcb144d6-2e72-11e8-8792-c2fc3f113200.png)

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

integrate the copy function in the header (right beside "add new") - similar to the copy function in the Content-Section

Danke Alex :-)

**Comment by alexander-schranz** [comment]
Implemented in https://github.com/sulu/SuluFormBundle/pull/316
