### ISSUE TITLE
MailChimp status

### ISSUE THREAD

**Issue by draganmilijasevic** [sulu/SuluFormBundle#166]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | 1.0.0-RC4
| Sulu Version | 1.6.3
| Browser Version | Browser name and version

#### Actual Behavior

How does it behave at the moment?
At the moment the default status of the post method is `subscribed`.

`$MailChimp->post('lists/' . $listId . '/members', [
                    'email_address' => $email,
                    'status' => 'subscribed',
                ]);` 

#### Expected Behavior

What is the behavior you expect?
The default status should be `pending`.

`$MailChimp->post('lists/' . $listId . '/members', [
                    'email_address' => $email,
                    'status' => 'subscribed',
                ]);`

#### Steps to Reproduce

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that reproduce the problem.

`MailchimpListSubscriber.php`

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)
Add as default `pending`.

**Comment by alexander-schranz** [comment]
fixed by #167
