### ISSUE TITLE
Mailchimp list select limited to 10

### ISSUE THREAD

**Issue by jurbar** [sulu/SuluFormBundle#176]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Bundle Version | 0.3.2
| Sulu Version | 1.6.21

#### Actual Behavior

It shows me up to 10 mailing lists

#### Expected Behavior

Show me all the mailing lists

#### Steps to Reproduce

1. Create 11 mailing lists in Mailchimp
2. Create a form with a Mailchimp field
3. Look at the lists you can select, this result is limited to 10 

#### Possible Solutions

10 is the default limit for the mailchimp API, this can be overwritten in the getMailChimpLists (\Sulu\Bundle\FormBundle\Dynamic\Types\MailchimpType::getMailChimpLists) function in the MailchimpType. (sulu/sulu-form-bundle/Dynamic/Types/MailchimpType.php)

`$response = $mailChimp->get('lists', ['count' => 100]);`

would show me up to 100 mailing lists, perhaps this could become a parameter or something like that so we have control over this.

**Comment by alexander-schranz** [comment]
@jurbar thanks for the report.
maybe we should increase the default to 50 or 100. not sure how many lists are mostly created. but make it configureable sounds good for me. you want to create a PR for this?

**Comment by jurbar** [comment]
If I find the time
