### ISSUE TITLE
Compatibility with ReCaptcha V3

### ISSUE THREAD

**Issue by Splodge77** [sulu/SuluFormBundle#180]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Sulu Version | ~1.6.22
| Browser Version | Chrome Version 70.0.3538.110 

Currently no immediate compatibility for ReCaptcha V3. When attempting to re-configure twig template for V3 standard, as seen in their documentation, the public key is rendered as a null value. I have attempted to adapt the validation as well but with little effect, which admittedly be down to inexperience with the subject.

#### Steps to Reproduce

Standard installation of Sulu using composer for both said bundle and the form bundle. Then installation fo the EWZ ReCaptcha bundle then usage of a V3 ReCaptcha public key. Then attempting to re-configure the bundle twig template in the standard fashion by making a copy of the file path in the resources directory of the app bundle. 

#### Possible Solutions

Hopefully a catch clause in the twig template that would allow a version 3 public key to be used or perhaps some more detailed description of the correct implementation in the documentation.

Thank you for your time and for making an otherwise very handy bundle.
M

**Comment by alexander-schranz** [comment]
Hello @Splodge77 
Which version of the bundle sulu form bundle and recaptcha bundle are you using?

**Comment by Splodge77** [comment]
Hi there @alexander-schranz, 

Currently using;
  sulu/sulu-form-bundle: ^0.4.0
  excelwebzone/recaptcha-bundle: ^1.5

Thanks for the quick response,
M

**Comment by alexander-schranz** [comment]
@Splodge77 this seems not to be a problem with the sulu form bundle the recaptcha bundle seems currently not supporting V3: have a look at https://github.com/excelwebzone/EWZRecaptchaBundle/issues/218
