### ISSUE TITLE
Compatibility issue with doctrine/orm 2.6

### ISSUE THREAD

**Issue by MichelFalke** [sulu/SuluFormBundle#181]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Bundle Version | all versions
| Sulu Version | all versions
| Browser Version | all versions

#### Actual Behavior

Doctrine ORM EntityRepository has added the function count. Since the FormRepository extends from it and has it's own count with multiple parameters this gives a conflict.

#### Expected Behavior

Don't conflict on inheritance

#### Steps to Reproduce

Update doctrine/orm to ^2.6

#### Possible Solutions

Rename the methods in the FormRepository
count becomes countByFilters
findAll becomes loadAll
findById becomes loadById

**Comment by alexander-schranz** [comment]
#182
