### ISSUE TITLE
Plain text variant for better spam score

### ISSUE THREAD

**Issue by kleinkoerkamp** [sulu/SuluFormBundle#187]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | 1.0.0-RC5 
| Sulu Version | 1.6.26
| Browser Version | Browser name and version

#### Actual Behavior

Now only an html variant is send to the customer. Mails with no text/plain variant get lower scores. See https://litmus.com/blog/best-practices-for-plain-text-emails-a-look-at-why-theyre-important.

#### Expected Behavior

Also a text/plain variant is send

#### Steps to Reproduce

Send mail via formbundle an validate via mailtester.com

#### Possible Solutions

I will create a Pull Request with simple text/plain variant.

**Comment by alexander-schranz** [comment]
Sounds for me like a good idea 👍
