### ISSUE TITLE
Add Sender to Mail

### ISSUE THREAD

**Issue by lkeijmel** [sulu/SuluFormBundle#194]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | 1.0.0

On some servers the mails send from Sulu forms end up in spam-folders because the 'envelope-from' header is missing in the message and is auto-generated on the server when sending a e-mail.

To fix this the sender must be added to the Swift_Message with setSender() in Mail/Helper.php. This can be the same as the from-address or maby make it configurable with a fallback to the from-address.

If I can find the time I will make a PR for it. At least if there isn't a reason why not to add it ;-)

**Comment by alexander-schranz** [comment]
@lkeijmel I'm not familiar with the envelope-from header but it seems to make sense. As you did find out correctly it need to be done in the [Mail/Helper.php](https://github.com/sulu/SuluFormBundle/blob/1.0.0-RC7/Mail/Helper.php#L90). I see no reason not to add this. 

ping @chirimoya @danrot

**Comment by danrot** [comment]
I am also not an email expert, but that sounds reasonable :slightly_smiling_face:
