### ISSUE TITLE
Form selection limited to 10 in Sulu 2.0

### ISSUE THREAD

**Issue by kleinkoerkamp** [sulu/SuluFormBundle#206]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | develop
| Sulu Version | 2.0.1

#### Actual Behavior

The 'single_form_selection' content type only returns the first 10 forms. So if you created 12 forms, the last 2 are not visible. 

#### Expected Behavior

All 12 forms are visible

#### Steps to Reproduce

Add 12 forms and try to show them in 'single_form_selection' content type

#### Possible Solutions

Default limit higher or another content type, like list-overlay.

**Comment by alexander-schranz** [comment]
closed via #207
