### ISSUE TITLE
Add form to another language

### ISSUE THREAD

**Issue by almare** [sulu/SuluFormBundle#208]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Bundle Version | dev
| Sulu Version | 2.0.1
| Browser Version | Browser name and version

#### Actual Behavior

At the moment it is not possible to reuse a contact form in a different language. The form is currently embedded in a block. This error appears.
```
Argument 1 passed to Symfony\Component\Form\FormRenderer::setTheme() must be an instance of Symfony\Component\Form\FormView, null given, 
```

#### Expected Behavior

After translating a form it should be possible to reuse the created form.

#### Steps to Reproduce

Create a form, translate it and assign it to a page.

**Comment by alexander-schranz** [comment]
@almare sorry could not reproduce this. Could you solve this and how?

**Comment by almare** [comment]
Sorry, me too. Probably it was my fault and maybe a misconfiguration. Somehow it started working. If I could I would describe what I have done. LOL Anyway this is the reason for closing this issue. Thank you for your response.
