### ISSUE TITLE
Add honeypot to forms

### ISSUE THREAD

**Issue by almare** [sulu/SuluFormBundle#212]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | Yes
| Sulu Version | 2.0
| Browser Version | Browser name and version

#### Actual Behavior

At the moment there is nor really useful spam prevention for forms there. Only recaptcha.

#### Possible Solutions
Add a honeypot form element for spammers. This should reduce the amount of form filler spammer.

**Comment by almare** [comment]
Ah, sorry. You are right.

**Comment by alexander-schranz** [comment]
@almare I did implement a configureable honeypot in #218 it would be great if you could give that a try and let me know if it fullfills your requirements.

**Comment by almare** [comment]
Awesome, I just made a short review of the code. It looks perfect from the point of configuration. I will test it the next days and give further response. Thank for spending time on it!!!

**Comment by almare** [comment]
This works as expected. Thank you.

**Comment by almare** [comment]
One comment. The field should not be required. If it's required the form could not be submitted!

**Comment by almare** [comment]
Just as feedback. Since I added your honeypot changes the spam is went down to ZERO! Hopefully this gets into the code.

**Comment by alexander-schranz** [comment]
@almare This is now merged and can now be used in `^2.0.0@dev` and will be release with the FormBundle 2.0 release.

**Comment by almare** [comment]
Perfect!!! Thank you for spending your time on this topic.
