### ISSUE TITLE
Email content layout

### ISSUE THREAD

**Issue by lucas-gymex** [sulu/SuluFormBundle#214]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Sulu Version | 2.0.1

Hello,

I'm in the process of finishing a project with Sulu, and I realized something about the email that we receive from the website via the contact form.

The email looks like this:
**Nom:** Test
**Prénom:** test
**E-mail:** test.email@outlook.fr
**Objet:** test email
**Message:** Etiam posuere vestibulum mi ut sollicitudin. Nullam eget faucibus dui. Fusce a purus sit amet risus porttitor tempus. Curabitur est lectus, ultrices ut eleifend nec, maximus a tortor. Fusce vestibulum rhoncus dui, eget auctor risus. Mauris bibendum scelerisque suscipit. Duis maximus euismod augue vitae porttitor.

The content of the message bothers me because it does not take into account the line breaks that we do when writing in the contact form.

What file should you overload in the bundle in order to fix this please? Or is there another solution?

Thank you for your answers

**Comment by alexander-schranz** [comment]
Think its the notify e-mail you can configure the email temlates in:

```
sulu_form
    mail:
        templates:
            notify:               'SuluFormBundle:mails:notify.html.twig'
            notify_plain_text:    'SuluFormBundle:mails:notify_plain_text.html.twig'
            customer:             'SuluFormBundle:mails:customer.html.twig'
            customer_plain_text:  'SuluFormBundle:mails:customer_plain_text.html.twig'
```

But think a `|nl2br` filter is missing [here](https://github.com/sulu/SuluFormBundle/blob/cc2a6bb8cc4b68d1828abc0f3f60360d1a9e805a/Resources/views/mails/notify.html.twig#L23)

**Comment by lucas-gymex** [comment]
Yes that was it 😃 thank you @alexander-schranz
