### ISSUE TITLE
Form field types are not sorted alphabetically

### ISSUE THREAD

**Issue by tvwijgerden** [sulu/SuluFormBundle#226]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Bundle Version | dev-develop
| Sulu Version | -
| Browser Version | -

#### Actual Behavior

When using a different language than English, the available form field types in the dropdown are not sorted alphabetically. 

#### Expected Behavior

No matter what language you use, the form field types should be sorted alphabetically.

#### Steps to Reproduce

Use another language than English and open the dropdown to select a form field type.

#### Possible Solutions

The `Sulu\Bundle\FormBundle\Metadata\DynamicFormMetadataLoader` class creates this array of form field types and sorts them by key. These keys are English which means the array will always based on the English names of the form fields.

A possible solution is to sort the field types by the `FormMetaData` title property. The title property contains the translated form field type which means sorting it by the title property would work.

Instead of this in `Sulu\Bundle\FormBundle\Metadata\DynamicFormMetadataLoader`:
```
$types = $this->formFieldTypePool->all();
ksort($types);
foreach ($types as $typeKey => $type) {
    $fields->addType($this->loadFieldTypeMetadata($typeKey, $type, $locale));
}
```
The solution would be replacing the code above with the following:
```
$types = $this->formFieldTypePool->all();

$fieldTypeMetaDataCollection = [];
foreach ($types as $typeKey => $type) {
    $fieldTypeMetaDataCollection[] = $this->loadFieldTypeMetadata($typeKey, $type, $locale);
}

usort($fieldTypeMetaDataCollection, function (FormMetadata $a, FormMetadata $b): int {
    return strcmp($a->getTitle(), $b->getTitle());
});

foreach ($fieldTypeMetaDataCollection as $fieldTypeMetaData) {
    $fields->addType($fieldTypeMetaData);
}
```

What do you think? If this is something you'd like to see changed, I can make a PR for it.

**Comment by alexander-schranz** [comment]
For me it would be great if sulu would provide something out of the box to sort block types alphabetically but until your workaround looks good for me.
