### ISSUE TITLE
Support new list filter configuration

### ISSUE THREAD

**Issue by Emilvooo** [sulu/SuluFormBundle#228]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | dev-develop
| Sulu Version | 2.1.*@dev
| Browser Version | 

#### Actual Behavior

It throws an error on the filter-type attribute. See: https://github.com/danrot/sulu/blob/89512c37e28213b4a386cfef8e1eba4838e7220f/UPGRADE.md

#### Expected Behavior

Sulu form bundle should work with Sulu 2.1.*@dev

#### Steps to Reproduce

Use the sulu form bundle in a project with Sulu 2.1.*@dev

#### Possible Solutions

Remove the filter-type attribute for now. In the UPDATE.md it states that this attribute is not yet in use at all. I will make a PR for this.

**Comment by alexander-schranz** [comment]
fixed
