### ISSUE TITLE
Order of fields is reset when saving

### ISSUE THREAD

**Issue by cirykpopeye** [sulu/SuluFormBundle#245]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 2.0.6
| Browser Version | Chrome

#### Actual Behavior

When changing order of form fields and saving the form the form fields get reset back to their original position, only until refresh of the page the fields get populated correctly again.

#### Expected Behavior

When saving, it should keep the order which was set before the saving.

#### Steps to Reproduce

1. Switch a field from position so the order changes
2. Click the save button

You should now see that the fields go back to their original position, on refresh you will see the correct changes.

#### Possible Solutions

Order the fields by order before returning the API response.

**Comment by alexander-schranz** [comment]
Fixed by #243 Thank you!
