### ISSUE TITLE
DynamicListBuilder breaks Listview

### ISSUE THREAD

**Issue by marcostastny** [sulu/SuluFormBundle#249]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Bundle Version | 9a43be625bbdf32e9a776782ec85fe8995934cb5 but c7f01fd47656bdfda4c82d6d25bb62db067c5f48 also has this issue
| Sulu Version | 2.0.6

#### Actual Behavior

When adding a Attachment Field and uploading this by a frontend form, the List View will Error with the following message:
```
Argument 1 passed to Sulu\Bundle\FormBundle\ListBuilder\DynamicListBuilder::getMediaUrls() must be of the type string, array given, called in /.../vendor/sulu/form-bundle/ListBuilder/DynamicListBuilder.php on line 57
```

In the Symfony Profiler nothing seems to be wrong during file upload.

```
[▼
  "attachment" => [▼
    Symfony\Component\HttpFoundation\File\UploadedFile {#25 ▼
      -test: false
      -originalName: "jonatan-pie-C2YORgsJqXs-unsplash (1).jpg"
      -mimeType: "image/jpeg"
      -error: 0
      path: "/private/var/tmp"
      filename: "phpkV9Xb3"
      basename: "phpkV9Xb3"
      pathname: "/private/var/tmp/phpkV9Xb3"
      extension: ""
      realPath: "/private/var/tmp/phpkV9Xb3"
      aTime: 2020-05-05 14:59:29
      mTime: 2020-05-05 14:59:29
      cTime: 2020-05-05 14:59:29
      inode: 42311052
      size: 1584286
      perms: 0100600
      owner: 1924723254
      group: 0
      type: "file"
      writable: true
      readable: true
      executable: false
      file: true
      dir: false
      link: false
    }
  ]
]
```

In the database the file looks as follows: `attachment: [20]`

#### Expected Behavior

List View should display normally.

#### Steps to Reproduce

As Stated above create a new Dynamic form with an attachment field in it. Display this form somewhere in the Frontend. Then upload a file using the field (we used Dropzone as plugin, i did not test html5 file input). After this the list view should break and throw a 500.

**Comment by alexander-schranz** [comment]
Thank for report can you test can you test #250

**Comment by marcostastny** [comment]
@alexander-schranz Thanks for the quick response, now i get the following error. `Parameter "id" for route "sulu_media.website.media.download" must match "\d+" ("{id}" given) to generate a corresponding URL.`

**Comment by alexander-schranz** [comment]
@marcostastny oh I see. #251 should fix that.

**Comment by marcostastny** [comment]
@alexander-schranz I can confirm that it works now, thank you very much.
