### ISSUE TITLE
"sulu_form.handler.saved" event changed to "sulu_form.handler.save"

### ISSUE THREAD

**Issue by manuxi** [sulu/SuluFormBundle#257]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | ^2.0@dev
| Sulu Version | ^2.1.0-RC1

#### Actual Behavior
It turns out that the (post save) event name has changed in the Form/Handler::save() method to FormSavePreEvent::NAME (https://github.com/sulu/SuluFormBundle/commit/891fad5a2eeb19f0f5b60a5c78a45f397ef3b4e7#diff-e392e14f8d51e1a2527499b02cb668b6) -  before there were two different events: "sulu_form.handler.save" and "sulu_form.handler.saved".

Now there is no unique event which is dispatched after saving. If I listen to FormSavePreEvent::NAME I could not use a message, perhaps the form is not valid.

#### Expected Behavior

Dispatch a unique event after saving.

#### Steps to Reproduce

Let an event listener listen to FormSavePostEvent::NAME - nothing happens.

#### Possible Solutions

Change it back.

**Comment by alexander-schranz** [comment]
It should definitly use the const from `FormSavePostEvent::NAME` do you want to create a PR?

**Comment by manuxi** [comment]
Ok, I'll try.
