### ISSUE TITLE
Form submission timer

### ISSUE THREAD

**Issue by RealAestan** [sulu/SuluFormBundle#294]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version |
| Sulu Version |
| Browser Version |

####

It would be nice to have a timer (customizable for each email) to submit again a form with a customizable error message when already sent within the timer.
Something like storing the form name in session could be done.

```
if (!$session->has('dynamic_form1') || $session->get('dynamic_form1') < new \DateTime()) {
    // Handle form submission
    $date = new \DateTime('+5 seconds');
    $session->set('dynamic_form1', $date);
} else {
    // Add a customisable error message when user already sent within the past 5 seconds
}
```

I think it would be a nice addition, I can develop it but I would like your opinion on that.

**Comment by alexander-schranz** [comment]
Hello @RealAestan,

Looks for me you are looking for a way to avoid double submitting of a form when somebody does double click the submit button. For avoiding spam we have recaptcha or the honey pot fields to avoid bots.

For double submitting I recommend you to disable the button on submit, you can do this in a custom JS component or directly on the form with something like this (untested):

```html
<form onsubmit="document.querySelector('button[type=submit]').disabled = true; return true;">
```

Still if you want to implement something like this in your project, you can implement a RequestListener and listen to FormEvents, we currently have no plans to add something like this to the form bundle, specially as we want avoid sessions on the website when possible. Still thank you for offering to implement it, we appreciate your offer a lot, but currently we don't think to add something like this to the form bundle.
