### ISSUE TITLE
Custom form validation, error message

### ISSUE THREAD

**Issue by RealAestan** [sulu/SuluFormBundle#296]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | 
| Sulu Version | 
| Browser Version | 

#### Feature

It would be nice if it was possible to set an error message for each field (translatable) for custom form validation.

**Comment by alexander-schranz** [comment]
What type of error message do you mean? The form bundle usage is for creating contact forms and things like this. Error messages for required fields can if it does not match, be changed when overwriting the translation.

What are you trying to achieve of what type of error message do you want to show and what type of custom form validation do you use, please provide an example use case.

**Comment by RealAestan** [comment]
I'm talking about the browser form validation messages.
For example for an email input field when the form is submitted I would like to show the user "An email is required to contact you back" when the field is incorrect. I want to do it via setCustomValidity https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/setCustomValidity and be able to have different validation message by field. Not just a generic message "This field is required". It could use a custom attr in the symfony field like "data-error-message".
Its also nice because the error message of the browser does not follow the language of the website but the language of the browser and this would follow the language of the website.

-------- Original Message --------
On Aug 12, 2021, 5:32 PM, Alexander Schranz < ***@***.***> wrote:
What type of error message do you mean? The form bundle usage is for creating contact forms and things like this. Error messages for required fields can if it does not match, be changed when overwriting the translation.
What are you trying to achieve of what type of error message do you want to show and what type of custom form validation do you use, please provide an example use case.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.￼
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/sulu/SuluFormBundle/issues/296#issuecomment-897738270">https://github.com/sulu/SuluFormBundle/issues/296#issuecomment-897738270", "url": "[https://github.com](<a href=)/sulu/SuluFormBundle/issues/296#issuecomment-897738270">https://github.com/sulu/SuluFormBundle/issues/296#issuecomment-897738270", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by RealAestan** [comment]
This kind of validation
-------- Original Message --------

**Comment by RealAestan** [comment]
This kind of validation
![Screenshot from 2021-08-12 19-17-42](https://user-images.githubusercontent.com/15686636/129240313-5f3ea848-6859-4396-a459-e543497f8f41.png)

**Comment by alexander-schranz** [comment]
@RealAestan you can achieve this things by overwriting the symfony form theme have a look at the https://symfony.com/doc/current/form/form_themes.html documentation. You can then there add additional attributes you want. You can also extend every form and form field in Symfony using the Symfony Form Extension: https://symfony.com/doc/current/form/create_form_type_extension.html.
