### ISSUE TITLE
implement a “copy locale” functionality

### ISSUE THREAD

**Issue by remdan** [sulu/SuluFormBundle#304]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | 2.0
| Sulu Version | ^2.2.0 
| Browser Version | All

#### Actual Behavior

A form cannot be copied for another language

#### Expected Behavior

It should behave the same as other things in sulu, not create a extra form for every language...

#### Steps to Reproduce

 I can change the language now, but then I see an empty form without text and in frontend it shows me nothing!

#### Possible Solutions

implement a “copy locale” functionality

**Comment by alexander-schranz** [comment]
Thank you for creating this issue. Its duplicated so I will close this one #151. Please upvote and subscribe the issue there.
