### ISSUE TITLE
Compatibility Sulu 2.5.0

### ISSUE THREAD

**Issue by cirykpopeye** [sulu/SuluFormBundle#330]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | 2.4.0
| Sulu Version | 2.5.0
| Browser Version | Chrome

#### Actual Behavior

Can't install the bundle due to conflicting dependencies, f.e. `sulu/form-bundle 2.4.0 requires symfony/config ^4.4 || ^5.0`

#### Steps to Reproduce

Install latest Sulu 2.5.0, and try  `composer require sulu/form-bundle`

#### Possible Solutions

Version bump of certain packages.

**Comment by TELLO0815** [comment]
Any progress/solution with Sulu 2.5.0 + SuluFormBundle?

**Comment by alexander-schranz** [comment]
Fixed in https://github.com/sulu/SuluFormBundle/pull/329 will be part of next release.
