### ISSUE TITLE
Invalid form field attributes (grid related)

### ISSUE THREAD

**Issue by fnagel** [sulu/SuluFormBundle#369]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | 2.5.2

#### Actual Behavior

Template renders form fields with invalid attributes like `<input type="text" width="half" widthnumber="6">`

#### Expected Behavior

Template should not render invalid attributes / attribute values like `width="half"` or `widthnumber`.

#### Steps to Reproduce

Just create any form field.

**Comment by alexander-schranz** [comment]
Make sure to extend with the providid form theme like documented which handles that for you: https://github.com/sulu/SuluFormBundle/blob/b01747b887e66a8dcfdfbee4332e5e329472f882/Resources/views/themes/basic.html.twig#L124

**Comment by fnagel** [comment]
I'm using an `use` statement for importing the default TWBS form theming which reverted those changes. I needed to add the referenced block again to make it work without issues.

No idea how I overlooked that one. Thanks for the hint and sorry for the invalid bug report.
