### ISSUE TITLE
Form fields in succession message (e-mail configuration in back-end)

### ISSUE THREAD

**Issue by AlexAlbersNL** [sulu/SuluFormBundle#371]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| Bundle Version | Specific version or SHA of a commit
| Sulu Version | Specific version or SHA of a commit
| Browser Version | Browser name and version

#### Actual Behavior

Currently you can create a succession message for the person that fills out the form. Unlike the email that is send to the email address that is entered in the "receiver" field (toEmail) in the e-mail configuration section in the back-end, this e-mail doesn't contain any entered data.

#### Expected Behavior

I would like to have the capability to add form fields in the succession message text field at the e-mail configuration section in the back-end.

#### Possible Solutions

I don't care how. But it can be easy as a {dropdown} or {text3} place holder coding I guess. I'm not a programmer ;-)

**Comment by alexander-schranz** [comment]
@AlexAlbersNL you have in the email template access to the form data so you could in the project do it and use the twig replace filter.

**Comment by alexander-schranz** [comment]
Closing this as its a developers task of the email which data is send to the admin task. By default the form bundle sends all form fields: 

https://github.com/sulu/SuluFormBundle/blob/92bb873dabc13cdb445e96b24cb383053a5a177e/Resources/views/mails/notify.html.twig#L1
