### ISSUE TITLE
Freetext fields have required constraints

### ISSUE THREAD

**Issue by oprichnik** [sulu/SuluFormBundle#379]
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| Bundle Version | 2.5.2
| Sulu Version | 2.5.10
| Browser Version | Firefox 125

#### Actual Behavior

When switching from a field with the "required" radio set, to a "freetext" field, the "required" radio disappears but the behaviour is still there and submitting the form trigger a required error on that field

#### Expected Behavior

No required constraint on freetext fields

#### Steps to Reproduce

1. Create a classic field and set the "required" on.
2. Switch this field to a "freetext" field
3. Save the form
4. Create a page including this form and try to send the form

#### Possible Solutions

Do not put any constraint on freetext fields

![image](https://github.com/sulu/SuluFormBundle/assets/6411030/6491551d-7059-493f-a5a7-19eb5bce1c04)

**Comment by alexander-schranz** [comment]
@oprichnik Thank you for the report I think we should do a check here for `HiddenType::class` to not set hidden fields with a notblank constraint:

https://github.com/sulu/SuluFormBundle/blob/b87895c44c701410fe84f4ddb44cace72b2cee7c/Form/Type/DynamicFormType.php#L117

Do you want to create a pull request for it.

**Comment by oprichnik** [comment]
Here it is: https://github.com/sulu/SuluFormBundle/pull/380
