### ISSUE TITLE
Sulu 2.6 compatibility

### ISSUE THREAD

**Issue by ehibes** [sulu/SuluFormBundle#381]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Bundle Version | Specific version or SHA of a commit
| Sulu Version | 2.6
| Browser Version | Browser name and version

We can't install this bundle due to a compatibility issue with Sulu 2.6.
https://github.com/sulu/SuluFormBundle/blob/2.5/composer.json#L24

**Comment by alexander-schranz** [comment]
@ehibes `^` means up to the next major version. This means `^2.4.1` include all from `2.4.1 - 2.99999999999...`. There is a nice website here to check composer verson constraints: https://semver.madewithlove.com/?package=sulu%2Fsulu&constraint=%5E2.4.1+%7C%7C+%5E2.5.0%40dev&stability=stable

You probably have another problem / conflict. Which mostly is `doctrine/persistence` package https://github.com/sulu/SuluFormBundle/pull/376 so at current state if you want to use a newer doctrine/persistence version you can currently use `^2.5@dev`.

**Comment by ehibes** [comment]
You're right, it's not a composer issue. But I have this : 
```

Problem 1
    - Root composer.json requires sulu/sulu ~2.6.1 -> satisfiable by sulu/sulu[2.6.1, 2.6.2].
    - Conclusion: install one of doctrine/doctrine-bundle[2.5.0, 2.5.1] (conflict analysis result)
    - Conclusion: don't install doctrine/doctrine-bundle 2.5.1 (conflict analysis result)
    - Conclusion: don't install doctrine/persistence 2.5.5 (conflict analysis result)
    - Conclusion: don't install doctrine/persistence 2.5.7 (conflict analysis result)
    - doctrine/persistence[2.2.1, ..., 2.5.1] require doctrine/deprecations ^0.5.3 -> found doctrine/deprecations[v0.5.3] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires sulu/form-bundle * -> satisfiable by sulu/form-bundle[0.1.0, ..., 0.4.0, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 2.0.0, ..., 2.5.2].
    - Root composer.json requires doctrine/doctrine-bundle ^2.5 -> satisfiable by doctrine/doctrine-bundle[2.5.0, ..., 2.12.0].
    - doctrine/doctrine-bundle 2.5.0 requires doctrine/persistence ^2.2 -> satisfiable by doctrine/persistence[2.2.0, ..., 2.5.7].
    - You can only install one version of a package, so only one of these can be installed: doctrine/persistence[v1.0.0, ..., 1.3.8, 2.0.0, ..., 2.5.7, 3.0.0, ..., 3.3.2].
    - Conclusion: install doctrine/persistence 3.1.1 (conflict analysis result)

You can also try re-running composer require with an explicit version constraint, e.g. "composer require sulu/form-bundle:*" to figure out if any version is installable, or "composer require sulu/form-bundle:^2.1" if you know which you need.
```

**Comment by alexander-schranz** [comment]
Did you try the #376 merge request with: `composer require "sulu/form-bundle:^2.5@dev"`.

**Comment by ehibes** [comment]
Ok, sorry I didn't understand I need to change branch of the package. 
`composer require "sulu/form-bundle:^2.5@dev" -W ` solves everything

**Comment by ehibes** [comment]
Thank you @alexander-schranz

**Comment by alexander-schranz** [comment]
We will make a release in the next time which allows you then go back to the normal version without the dev postfix.
