### ISSUE TITLE
Add error-handling on send mail.

### ISSUE THREAD

**Issue by dominikmatt** [sulu/SuluFormBundle#64]
On connection error with SMTP connection we doesn't get any errors in log files.

**Solution:**
https://github.com/sulu/SuluFormBundle/blob/develop/Mail/Helper.php#L123
```
$failed = null;
$return = $this->mailer->send($message, $failed);

$this->logger->error(var_export($failed));

return $return;
```

**Comment by alexander-schranz** [comment]
this will always log an error. For me it doesnt make sense to log error which are logged by the swiftmailer bundle so its just a duplicated error message. And Emails are not send when you call `send` function, emails are send in the kernel terminate normally on production.
