### ISSUE TITLE
Rename placeholder to example 

### ISSUE THREAD

**Issue by dmetzler1988** [sulu/SuluFormBundle#67]
Since the placeholder shouldn't be used as placeholder, rename the field `Placeholder` to `Example`. It should be used as example field under the form-field like:

Label
Input
Example

Don't miss to add a documentation for the usage if the field should have a placeholder (use the title field as placeholder-item - in case of the required attribute)

![bildschirmfoto 2017-03-15 um 14 15 23](https://cloud.githubusercontent.com/assets/8446518/23950028/ea94d75a-0989-11e7-9175-b0430545287b.png)

**Comment by dmetzler1988** [comment]
misunderstanding the input - so this issue can be closed :)

**Comment by alexander-schranz** [comment]
As said it should be renamed because when the `Theme` use the title to be displayed the Label as Placeholder the current placeholder should be set as example after the input field.

This would look like this:

```
+---------------------+
| Firstname           |
+---------------------+
e.g.:  Hikaru

+---------------------+
| Lastname           |
+---------------------+
e.g.: Sulu

+---------------------+
| Email               |
+---------------------+
e.g.: hikaru@sulu.io
```

And then the naming placeholder doesnt make sense any more and should be `example`.
