### ISSUE TITLE
Parameter "type" is missing on "form_select"

### ISSUE THREAD

**Issue by codebarista** [sulu/SuluFormBundle#84]
After updating to version 0.2.0 (or @dev) I get the following message:

> An exception has been thrown during the rendering of a template ("SuluFormBundle: The parameter "type" is missing on "form_select" content-type.").

To reproduce, it is sufficient to add a form to a page.

**Comment by codebarista** [comment]
Sorry, it was written there:
https://github.com/sulu/SuluFormBundle/blob/master/Resources/doc/dynamic.md#basic-sulu-template

Everything good. Thanks.

**Comment by alexander-schranz** [comment]
Wünsch upgrading Always have a Look at the UPGRADE.md https://github.com/sulu/SuluFormBundle/blob/master/UPGRADE.md#set-type-for-content-type-definition
