### ISSUE TITLE
Add field for tracking JS on submit

### ISSUE THREAD

**Issue by matt-halliday** [sulu/SuluFormBundle#93]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| SuluFormBundle Version | `dev-feature/symfony-3-release`
| Sulu Version | 1.6.2

#### Actual Behavior

Sulu does not support analytics code and conversions.

#### Desired Behavior

A plain text field to be added for code to execute on successful submission. This would allow arbitrary javascript or IDs to be added for tracking form interaction.

**Comment by alexander-schranz** [comment]
@matt-halliday this sounds like frontend logic. The form bundle will not care about your frontend use form theming http://symfony.com/doc/current/form/form_customization.html set ids you just need to extend from the basic theme.  https://github.com/sulu/SuluFormBundle/blob/master/Resources/doc/theming.md.

Executing JavaScript is part of the Dev the content manager should not know about JS. If you really want it add a textarea to your page Template and execute that code on the success page.

**Comment by matt-halliday** [comment]
@alexander-schranz ok - agreed about separation. Because of the way I'm using forms currently, one form may appear on many pages/blocks which would mean duplication of pasting tracking/conversion IDs. Maybe I'll add a snippet type or something for them so that they can be managed centrally.

**Comment by alexander-schranz** [comment]
@matt-halliday in your case I would register a [new tab](http://docs.sulu.io/en/latest/cookbook/using-tab-navigation.html) to the form entity create a custom form analytics entity where the content manager can add this data to the form.
