### ISSUE TITLE
Form-Tab not working with static Forms

### ISSUE THREAD

**Issue by dominikmatt** [sulu/SuluFormBundle#95]
| Q | A
| --- | ---
| Bug? | yes
| Sulu Version | 1.5.4
| SuluFormBundle Version | 0.2.2

#### Actual Behavior

Form-Tab on Content-page not visible.

#### Possible Solutions

Register ` TemplateNavigationProvider` on your `service.xml`.
```
<service id="client_website.list.provider" class="Sulu\Bundle\FormBundle\Admin\TemplateNavigationProvider">
    <argument type="service" id="sulu.list.provider.registry"/>

    <tag name="sulu_admin.content_navigation" alias="content" />
</service>
```

**Comment by alexander-schranz** [comment]
For static forms you need to create a [sulu_form.list_provider](
https://github.com/sulu/SuluFormBundle/blob/master/Resources/doc/static.md#create-a-listprovider-optional)

which need to be tagged as:

```xml
<tag name="sulu_form.list_provider" template="pages_template_key" />
```
